config/routes.rb
Rails.application.routes.draw do
  resources :games

  resources :charges

  root to: 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    game = Game.find(params[:game_id])

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: game.price.to_s.delete('.').to_i,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1 class="display-1 text-center">Games</h1>

<div class="game-container">
  <% @games.each do |game| %>
    <div class="card">
      <div class="card-body">
        <h3 class="card-title"><%= game.name %></h3>
        <p class="card-subtitle text-success"><%= game.price %></p>
        <%= link_to "View", game_path(game), class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/games/show.html.erb
<h1 class="display-2 text-center"><%= @game.name %></h1>

<p>Price: <%= @game.price %></p>

<%= render 'shared/stripe_form', game: @game %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_stripe_form.html.erb
<%= form_tag charges_path do %>
  <%= hidden_field_tag(:game_id, game.id) %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span><%= game.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Purchase <%= game.name %>"
          data-amount=<%= game.price.to_s.delete('.').to_i %>
          data-locale="auto"></script>
<% end %>